name: DemoApp
options:
  bundleIdPrefix: de.silpion.ohcapp4ios
settings:
  base:
    GENERATE_INFOPLIST_FILE: YES
    DEVELOPMENT_TEAM: 67X5G8WXSG
    CURRENT_PROJECT_VERSION: -1
    SWIFT_VERSION: 5.0
    ALWAYS_SEARCH_USER_PATHS: NO
    FRAMEWORK_SEARCH_PATHS: "$(inherited)"
  configs:
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
    Debug:
      SWIFT_COMPILATION_MODE: incremental
targets:
  DemoApp:
    type: application
    platform: iOS
    deploymentTarget: "16.6"
    settings:
      base:
        SWIFT_VERSION: $(inherited)
        ALWAYS_SEARCH_USER_PATHS: $(inherited)
        PRODUCT_NAME: DemoApp
        CODE_SIGN_ENTITLEMENTS: DemoApp/DemoApp.entitlements
      Release:
        SWIFT_COMPILATION_MODE: wholemodule
      Debug:
        SWIFT_COMPILATION_MODE: incremental
    sources:
      - DemoApp
      - path: DemoApp/Generated/R.generated.swift
        type: file
    dependencies:
      - framework: Carthage/Build/DataKit.xcframework
        embed: true
        codeSign: true
      - framework: Carthage/Build/GemCommonsKit.xcframework
        embed: true
        codeSign: true
      - framework: Carthage/Build/ObjCCommonsKit.xcframework
        embed: true
        codeSign: true
      - framework: Carthage/Build/CardReaderProviderApi.xcframework
        embed: true
        codeSign: true
      - framework: Carthage/Build/CardReaderAccess.xcframework
        embed: true
        codeSign: true
      - framework: Carthage/Build/Rswift.xcframework
        embed: true
        codeSign: true
      - framework: Carthage/Build/Swinject.xcframework
        embed: true
        codeSign: true
      - framework: Carthage/Build/SnapKit.xcframework
        embed: true
        codeSign: true
      - framework: Carthage/Build/SwiftSocket.xcframework
        embed: true
        codeSign: true
      - framework: Carthage/Build/NFCCardReaderProvider.xcframework
        embed: true
        codeSign: true
      - framework: Carthage/Build/ASN1Kit.xcframework
        embed: true
        codeSign: true
      - framework: Carthage/Build/HealthCardAccess.xcframework
        embed: true
        codeSign: true
      - framework: Carthage/Build/HealthCardControl.xcframework
        embed: true
        codeSign: true
#      - framework: Carthage/Build/BigInt.xcframework
#        embed: true
#        codeSign: true
      - sdk: CoreNFC.framework
    preBuildScripts:
      - script: |
                ${SRCROOT}/tools/rswift generate ${SRCROOT}/DemoApp/Generated/R.generated.swift
        name: Run Script (R.swift)
        inputFiles:
          - $(TEMP_DIR)/rswift-lastrun
        outputFiles:
          - $(SRCROOT)/DemoApp/Generated/R.generated.swift
    scheme:
      testTargets:
        - DemoAppTests
        - DemoAppUITests
      gatherCoverageData: true
  DemoAppTests:
    type: bundle.unit-test
    platform: iOS
    sources: [DemoAppTests]
    dependencies:
      - target: DemoApp
  DemoAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [DemoAppUITests]
    dependencies:
      - target: DemoApp
buildImplicitDependencies: true
